openapi: 3.1.1
info:
  title: "ClickHouse Migration Implementation Plan"
  description: |
    Migration from QuestDB to ClickHouse for future-proofing and ecosystem maturity,
    following ADR-0005 decision to prioritize long-term scalability and robustness.

    Preserves zero-gap guarantee via application-level deterministic versioning.
    ReplacingMergeTree engine with _version column ensures consistent deduplication.

    This plan implements:
    - Schema design: ReplacingMergeTree with LowCardinality columns
    - Connection layer: clickhouse-driver Python client
    - Ingestion rewrite: Deterministic versioning for zero-gap guarantee
    - Query API rewrite: FINAL keyword for deduplicated results
    - Empirical validation: Re-run ADR-0003 suite (53.7M rows)
    - Futures support: Adapt ADR-0004 instrument_type implementation
    - Migration guide: QuestDB → ClickHouse transition documentation
  version: "1.0.0"
  x-adr-id: "0005"
  x-status: "implemented"
  x-phase-status:
    phase-1: "completed"
    phase-2: "completed"
    phase-3: "completed"
    phase-4: "completed"
    phase-5: "completed"
    phase-6: "completed"
    phase-7: "completed"
  x-target-release: "4.0.0"
  x-validation-date: "2025-11-17"
  x-validation-results:
    total-checks: 15
    passed: 15
    failed: 0
    success-rate: "100.0%"
  x-breaking-change: true
  x-depends-on: ["0003", "0004"]

paths: {}

x-implementation-plan:
  timeline:
    total_duration: "5 working days"
    estimated_hours: 35
    start_date: "TBD"
    target_completion: "TBD"

  phases:
    - id: "phase-1"
      name: "ClickHouse Schema Design"
      duration: "3 hours"
      status: "pending"
      deliverables:
        - name: "ClickHouse Schema SQL"
          paths:
            - "src/gapless_crypto_data/clickhouse/schema.sql"
          description: |
            CREATE TABLE statement for ClickHouse ohlcv table using ReplacingMergeTree
            engine with _version column for deterministic deduplication.
          acceptance_criteria:
            - "ReplacingMergeTree(_version) engine configured"
            - "ORDER BY (timestamp, symbol, timeframe, instrument_type)"
            - "PARTITION BY toYYYYMMDD(timestamp) for daily partitions"
            - "LowCardinality(String) for symbol, timeframe, instrument_type, data_source"
            - "_version UInt64 and _sign Int8 columns added"
            - "DateTime64(3) for millisecond precision timestamps"

        - name: "Docker Compose Configuration"
          paths:
            - "docker-compose.yml"
          description: "ClickHouse container setup for local development"
          acceptance_criteria:
            - "ClickHouse server on port 9000 (native protocol)"
            - "HTTP interface on port 8123"
            - "Volume mounting for data persistence"
            - "Health check configured"

    - id: "phase-2"
      name: "ClickHouse Connection Layer"
      duration: "4 hours"
      status: "pending"
      dependencies: ["phase-1"]
      deliverables:
        - name: "Connection Module"
          paths:
            - "src/gapless_crypto_data/clickhouse/connection.py"
            - "src/gapless_crypto_data/clickhouse/__init__.py"
          description: |
            ClickHouseConnection class with clickhouse-driver client, health checks,
            and error handling. Follows same pattern as QuestDBConnection.
          acceptance_criteria:
            - "ClickHouseConnection class with __enter__/__exit__ context manager"
            - "execute() method for SQL queries with parameter substitution"
            - "insert_dataframe() method for bulk inserts"
            - "Health check via SELECT 1 query"
            - "Connection pooling configured"
            - "Error handling raises and propagates (no silent failures)"

        - name: "Configuration Management"
          paths:
            - "src/gapless_crypto_data/clickhouse/config.py"
          description: "ClickHouse connection configuration (host, port, credentials)"
          acceptance_criteria:
            - "Environment variable support (CLICKHOUSE_HOST, CLICKHOUSE_PORT)"
            - "Defaults: localhost:9000"
            - "Validation for required parameters"

    - id: "phase-3"
      name: "Ingestion Rewrite with Deterministic Versioning"
      duration: "10 hours"
      status: "pending"
      dependencies: ["phase-2"]
      deliverables:
        - name: "ClickHouse Bulk Loader"
          paths:
            - "src/gapless_crypto_data/collectors/clickhouse_bulk_loader.py"
          description: |
            Rewrite of QuestDBBulkLoader for ClickHouse with application-level
            deduplication via deterministic _version hashing.
          acceptance_criteria:
            - "_prepare_clickhouse_row() adds deterministic _version hash"
            - "_version computed from (timestamp, OHLCV, symbol, timeframe, instrument_type)"
            - "_sign = 1 for all active rows"
            - "Preserves CloudFront download + ZIP extraction logic (from QuestDB version)"
            - "Handles both spot (11-column) and futures (12-column) CSV formats"
            - "instrument_type parameter preserved (defaults to 'spot')"
            - "Bulk insert via client.insert_dataframe()"
            - "Error handling: raise and propagate (no silent failures)"

        - name: "Deduplication Tests"
          paths:
            - "tests/collectors/test_clickhouse_deduplication.py"
          description: "Test deterministic versioning ensures zero-gap guarantee"
          acceptance_criteria:
            - "Test identical rows produce identical _version values"
            - "Test duplicate writes merge correctly in ClickHouse"
            - "Test FINAL keyword returns deduplicated results"
            - "Test cross-partition deduplication behavior"

    - id: "phase-4"
      name: "Query API Rewrite"
      duration: "6 hours"
      status: "pending"
      dependencies: ["phase-2"]
      deliverables:
        - name: "ClickHouse Query Module"
          paths:
            - "src/gapless_crypto_data/query.py"
          description: |
            Update OHLCVQuery class to use ClickHouse SQL syntax with FINAL keyword
            for deduplication. Preserve API signatures (backwards compatible).
          acceptance_criteria:
            - "get_latest() updated with ClickHouse syntax + FINAL keyword"
            - "get_range() updated with ClickHouse syntax + FINAL keyword"
            - "get_multi_symbol() updated with ClickHouse syntax + FINAL keyword"
            - "instrument_type parameter preserved (from ADR-0004)"
            - "Placeholder syntax: %(name)s instead of ?"
            - "Error handling: raise psycopg.Error → raise clickhouse_driver.Error"
            - "API signatures unchanged (backwards compatible)"

        - name: "Query Performance Tests"
          paths:
            - "tests/query/test_clickhouse_query_performance.py"
          description: "Benchmark FINAL keyword performance overhead"
          acceptance_criteria:
            - "Measure query latency with vs without FINAL"
            - "Document 10-30% overhead (acceptable trade-off)"
            - "Verify deduplicated results correctness"

    - id: "phase-5"
      name: "Empirical Validation (Re-run ADR-0003 Suite)"
      duration: "8 hours"
      status: "pending"
      dependencies: ["phase-3", "phase-4"]
      deliverables:
        - name: "ClickHouse Ingestion Validation"
          paths:
            - "tmp/clickhouse-validation/ingestion/ingest_comprehensive.py"
          description: |
            Re-run ADR-0003 comprehensive ingestion (53.7M rows) with ClickHouse.
            Copy from tmp/schema-robustness/ingestion/ and adapt for ClickHouse.
          acceptance_criteria:
            - "Ingest 5 symbols × 16 timeframes × 122 days successfully"
            - "Total rows: 53,726,725 (matches ADR-0003 QuestDB validation)"
            - "Zero ingestion errors (raise and propagate policy)"
            - "Ingestion rate: >100K rows/sec (SLO)"
            - "All 80 symbol-timeframe combinations present"

        - name: "ClickHouse Validation Agents"
          paths:
            - "tmp/clickhouse-validation/validation/01_schema_extensibility_agent.py"
            - "tmp/clickhouse-validation/validation/02_multi_symbol_stress_agent.py"
            - "tmp/clickhouse-validation/validation/03_temporal_boundary_agent.py"
            - "tmp/clickhouse-validation/validation/04_timeframe_spectrum_agent.py"
            - "tmp/clickhouse-validation/validation/05_deduplication_agent.py"
            - "tmp/clickhouse-validation/validation/06_query_performance_agent.py"
          description: |
            Adapt ADR-0003 validation agents for ClickHouse. Copy from
            tmp/schema-robustness/validation/ and modify for ClickHouse SQL syntax.
          acceptance_criteria:
            - "01: Validate ReplacingMergeTree schema, LowCardinality columns"
            - "02: Validate all 5 symbols present with identical row counts"
            - "03: Validate temporal boundaries (year transition, leap year, month boundaries)"
            - "04: Validate all 16 timeframes present (including 1mo)"
            - "05: Validate deterministic _version deduplication with FINAL"
            - "06: Benchmark query performance with FINAL keyword"
            - "All agents pass (zero failures)"

        - name: "Validation Report"
          paths:
            - "tmp/clickhouse-validation/reports/VALIDATION_SUMMARY.md"
          description: "Summary report comparing ClickHouse vs QuestDB validation results"
          acceptance_criteria:
            - "Document row counts match (53,726,725)"
            - "Document ingestion rate comparison (ClickHouse vs QuestDB)"
            - "Document query performance with FINAL overhead"
            - "Document zero-gap guarantee validation results"
            - "Recommendation: ✅ ClickHouse production-ready or ❌ issues found"

    - id: "phase-6"
      name: "Futures Support Adaptation"
      duration: "3 hours"
      status: "pending"
      dependencies: ["phase-5"]
      deliverables:
        - name: "Futures Support Integration"
          paths:
            - "src/gapless_crypto_data/collectors/clickhouse_bulk_loader.py"
          description: |
            Ensure ADR-0004 futures support (instrument_type column, 12-column CSV)
            works correctly with ClickHouse ReplacingMergeTree.
          acceptance_criteria:
            - "instrument_type parameter preserved in ClickHouseBulkLoader"
            - "instrument_type included in ORDER BY keys"
            - "instrument_type included in _version hash computation"
            - "Spot/futures isolation verified (no cross-contamination)"
            - "Query API filters by instrument_type correctly"

        - name: "Futures Validation Test"
          paths:
            - "tests/integration/test_clickhouse_futures.py"
          description: "Integration test for spot + futures coexistence in ClickHouse"
          acceptance_criteria:
            - "Ingest spot and futures data for same symbol/timeframe/timestamp"
            - "Verify ReplacingMergeTree deduplicates within instrument_type (not across)"
            - "Verify query filters work correctly (instrument_type='spot' vs 'futures')"
            - "Verify zero DEDUP collisions between spot and futures"

    - id: "phase-7"
      name: "Documentation and Migration Guide"
      duration: "1 hour"
      status: "pending"
      dependencies: ["phase-6"]
      deliverables:
        - name: "ClickHouse Migration Guide"
          paths:
            - "docs/guides/CLICKHOUSE_MIGRATION.md"
          description: "Step-by-step guide for migrating from QuestDB to ClickHouse"
          acceptance_criteria:
            - "Prerequisites: ClickHouse installation (Docker or native)"
            - "Schema migration: Run schema.sql script"
            - "Data migration: Export QuestDB → Import ClickHouse (if needed)"
            - "Validation steps: Run validation suite"
            - "Troubleshooting: Common issues and solutions"

        - name: "API Documentation Update"
          paths:
            - "docs/guides/python-api.md"
          description: "Update API docs with ClickHouse-specific details"
          acceptance_criteria:
            - "Document ClickHouseConnection usage"
            - "Document FINAL keyword requirement for deduplicated queries"
            - "Document _version and _sign columns (internal, not user-facing)"
            - "Document zero-gap guarantee preservation strategy"

        - name: "README Update"
          paths:
            - "README.md"
          description: "Update README with ClickHouse as primary database"
          acceptance_criteria:
            - "Update 'Database' section: ClickHouse (was QuestDB)"
            - "Update installation instructions for ClickHouse"
            - "Update performance metrics with ClickHouse results"

x-slos:
  availability:
    metrics:
      - name: "ClickHouse Service Availability"
        target: "99.9% uptime for ClickHouse service"
        measurement: "Docker health checks + connection retry validation"

      - name: "Backwards Compatibility"
        target: "API signatures unchanged from v3.x"
        measurement: "get_range(), get_latest(), get_multi_symbol() preserve instrument_type parameter"

  correctness:
    metrics:
      - name: "Zero-Gap Guarantee (ClickHouse)"
        target: "100% zero-gap guarantee via deterministic versioning"
        measurement: "Validation agent 05 confirms FINAL queries return deduplicated results"

      - name: "Deterministic Deduplication"
        target: "Identical writes produce identical _version values"
        measurement: "Test duplicate writes merge correctly, no non-deterministic outcomes"

      - name: "Futures Isolation"
        target: "Zero collisions between spot and futures data"
        measurement: "Spot and futures with same symbol/timeframe/timestamp coexist without DEDUP conflict"

  observability:
    metrics:
      - name: "Ingestion Metrics Logging"
        target: "All ingestion operations logged at INFO level"
        measurement: "Logs include: rows ingested, _version hash range, ingestion rate"

      - name: "Query Performance Monitoring"
        target: "FINAL keyword overhead documented and monitored"
        measurement: "Validation agent 06 benchmarks query latency with/without FINAL"

  maintainability:
    metrics:
      - name: "Code Reuse from QuestDB"
        target: "Minimize code duplication, reuse CloudFront download logic"
        measurement: "<500 lines changed (schema, connection, ingestion, query)"

      - name: "Validation Coverage"
        target: "95% test coverage for ClickHouse-specific code"
        measurement: "pytest-cov reports 95%+ for clickhouse_bulk_loader.py, query.py"

x-error-handling:
  policy: "raise-and-propagate"
  rationale: "All errors surface immediately to prevent silent data corruption or migration failures."
  examples:
    - scenario: "ClickHouse connection fails"
      behavior: "ClickHouseConnection.__init__() raises ConnectionError with host/port details"
      no_fallback: "Does NOT fall back to QuestDB, does NOT use default connection"
      propagation: "Error bubbles to caller, exits with non-zero status code"

    - scenario: "Duplicate writes with different _version (non-deterministic hash bug)"
      behavior: "Validation agent 05 detects inconsistency, raises AssertionError"
      no_retry: "Does NOT retry ingestion, does NOT ignore inconsistency"
      propagation: "Halts validation, reports bug in deterministic versioning logic"

    - scenario: "ReplacingMergeTree merge fails midway"
      behavior: "ClickHouse raises exception, no partial merge state"
      no_default: "Does NOT proceed with unmerged data, does NOT commit partial state"
      propagation: "Query with FINAL returns last known good state, error logged"

x-oss-libraries:
  - name: "clickhouse-driver"
    usage: "ClickHouse native protocol client for ingestion and queries"
    version: ">=0.2.0"

  - name: "pandas"
    usage: "DataFrame operations for CSV parsing and bulk inserts"
    version: ">=2.0.0"

  - name: "docker-compose"
    usage: "ClickHouse container orchestration for local development"
    version: ">=2.0.0"

x-auto-validation:
  artifacts:
    - name: "ADR-0005 and plan.yaml cross-reference"
      validation: "grep 'x-adr-id: \\\"0005\\\"' docs/plan/0005-clickhouse-migration/plan.yaml"

    - name: "ClickHouse schema validation"
      validation: "clickhouse-client --query 'SHOW CREATE TABLE ohlcv' | grep 'ReplacingMergeTree'"

    - name: "Deterministic versioning smoke test"
      validation: "python -c 'import gapless_crypto_data.collectors.clickhouse_bulk_loader; print(hash(\"test\") & 0xFFFFFFFFFFFFFFFF)'"

    - name: "Validation suite pass rate"
      validation: "All 6 validation agents pass (zero failures)"

x-semantic-release:
  enabled: true
  breaking_change: true
  release_type: "major"
  target_version: "v4.0.0"
  commit_convention: "conventional-commits"
  changelog_sections:
    - type: "feat"
      section: "Features"
      notes: "BREAKING: Database engine changed from QuestDB to ClickHouse"

    - type: "fix"
      section: "Bug Fixes"

    - type: "docs"
      section: "Documentation"

x-compliance:
  openapi_version: "3.1.1"
  doc_style: "evolutionary-without-promo"
  slo_focus: "availability, correctness, observability, maintainability"
  error_policy: "raise-propagate-no-fallback"
  oss_preference: "prefer-oss-over-custom"
  auto_validate: "all-artifacts-validated"
  release_automation: "semantic-release-conventional-commits"
  adr_plan_sync: "x-adr-id cross-reference validated"
